### ISSUE TITLE
Error log generated when killing "npm start" with Ctrl+C

### ISSUE THREAD

**Issue by pllim** [IUSCA/ADASS_tutorial_pre#3]
Following the instructions to press Ctrl+C to kill `npm start`, an error log was generated. Not sure what this means. It is attached below.

[2018-11-09T21_48_07_034Z-debug.log](https://github.com/IUSCA/ADASS_tutorial_pre/files/2567631/2018-11-09T21_48_07_034Z-debug.log)

**Comment by pllim** [comment]
(p.s. I accidentally posted the issue before finished typing. I have gone back and edited it properly.)

**Comment by agopu** [comment]
@pllim Are you able to execute 'npm start' again after you encounter that error (up on Ctrl + C'ing)?

**Comment by pllim** [comment]
Yes, it appears so.

```
$ npm start

> adass-demo-pre@0.0.1 start C:\...\ADASS_tutorial_pre
> node ./bin/www

Initializing database connection....

Successfully connected to database
Running on localhost:3000 in development mode
```

**Comment by agopu** [comment]
In that case, it might be safe to ignore (though I am usually averse to ignoring an error - in this case, NPM itself says this might be safe to ignore) it. :-)
