### ISSUE TITLE
Suggestion: Helper logistics 

### ISSUE THREAD

**Issue by pllim** [IUSCA/ADASS_tutorial_pre#8]
May I suggest having more than 1 helper and use the sticky notes system like Software Carpentry (i.e., put up yellow sticky note when done with a step or red sticky note when need help). 1 helper for every 15 participants would be ideal, if feasible. Just a thought.

**Comment by agopu** [comment]
Thanks for the suggestion, again, we will consider it for future tutorials. It was nice to meet you back in Nov. Closing this issue.
